import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useTooltipStore = defineStore('tooltip', () => {
    const visible = ref(false);
    const title = ref('');
    const content = ref('');
    const hint = ref('');
    const x = ref(0);
    const y = ref(0);
    const timeout = ref(null);

    // Contextual Wiki Knowledge
    const wikiTerms = {
        'rack': {
            title: 'Server Rack [Enclosure]',
            content: 'Standardized enclosures for mounting servers and networking gear. Rack capacity is measured in Rack Units (U).',
            hint: 'Manage rack thermal load to prevent throttling.'
        },
        'server': {
            title: 'Compute Node',
            content: 'The core hardware unit that executes client workloads and generates revenue. Requires power and generates heat.',
            hint: 'Check MTBF to avoid unplanned outages.'
        },
        'network': {
            title: 'Network Uplink',
            content: 'The data bridge between your servers and the global internet. Bandwidth limits the number of active high-traffic contracts.',
            hint: 'Expand uplinks to avoid congestion.'
        },
        'cooling': {
            title: 'Thermal Management',
            content: 'Environmental systems required to dissipate heat generated by compute cycles. Efficiency reduces power costs.',
            hint: 'Thermal overflow leads to hardware damage.'
        }
    };

    function show(event, optionsOrTerm) {
        if (timeout.value) clearTimeout(timeout.value);

        timeout.value = setTimeout(() => {
            let options = optionsOrTerm;

            // Handle string term lookup
            if (typeof optionsOrTerm === 'string' && wikiTerms[optionsOrTerm.toLowerCase()]) {
                options = wikiTerms[optionsOrTerm.toLowerCase()];
            }

            title.value = options.title || '';
            content.value = options.content || '';
            hint.value = options.hint || '';

            // Position
            const rect = event.target.getBoundingClientRect();
            x.value = rect.left + rect.width / 2;
            y.value = rect.top;

            visible.value = true;
        }, 300);
    }

    function hide() {
        if (timeout.value) clearTimeout(timeout.value);
        visible.value = false;
    }

    return { visible, title, content, hint, x, y, show, hide };
});
